[Base]
ValueType=Float
DistCalcMethod=L2
IndexAlgoType=BKT
Dim=128
VectorPath=/media/ray/1tb/sift1m/sift_base.fvecs
IndexDirectory=/media/ray/1tb/sift1m/bkt_memory_index

[Index]
; BKT树参数
TreeNumber=1
BKTKmeansK=32
BKTLeafSize=8
Samples=1000

; 图构建参数
NeighborhoodSize=32
TPTNumber=8
TPTLeafSize=2000
MaxCheckForRefineGraph=512
RefineIterations=1

; 线程数（可通过命令行覆盖：Index.NumberOfThreads=N）
NumberOfThreads=8
