#!/usr/bin/env python3
import argparse
import csv
import os
from typing import Dict, Iterable, List


METRICS = [
    "recall",
    "total_latency_ms",
    "head_latency_ms",
    "ex_latency_ms",
    "batch_read_total_ms",
    "truth_count",
    "coarse_recall",
    "coarse_recall_after_dedupe",
    "rerank_recall",
    "final_recall",
    "truth_recovered_by_head_result",
    "truth_dropped_per_posting_topr",
    "truth_dropped_global_topr",
    "truth_dropped_rerank_topk",
    "truth_missing_not_observed_in_scanned_posting",
    "truth_missing_not_in_posting_reserved",
    "unique_payload_pages",
    "payload_candidates",
    "postings_with_payload",
    "total_payload_page_spans",
    "pages_read",
    "requested_read_bytes",
    "payload_physical_bytes",
    "payload_logical_bytes",
    "distance_evaluated_count",
    "rerank_candidate_count",
    "coarse_candidate_count_before_dedupe",
    "coarse_candidate_count_after_dedupe",
]


def parse_float(value: str) -> float:
    if value == "" or value is None:
        return 0.0
    return float(value)


def mean(values: Iterable[float]) -> float:
    values = list(values)
    if not values:
        return 0.0
    return sum(values) / len(values)


def summarize_csv(path: str) -> Dict[str, float]:
    sums: Dict[str, float] = {metric: 0.0 for metric in METRICS}
    count = 0

    with open(path, newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            count += 1
            for metric in METRICS:
                if metric in row:
                    sums[metric] += parse_float(row[metric])

    summary = {metric: (sums[metric] / count if count else 0.0) for metric in METRICS}
    summary["query_count"] = float(count)
    summary["candidates_per_payload_page"] = (
        summary["payload_candidates"] / summary["unique_payload_pages"]
        if summary["unique_payload_pages"] > 0
        else 0.0
    )
    summary["truth_attribution_closure_error"] = (
        summary["final_recall"]
        + summary["truth_dropped_per_posting_topr"]
        + summary["truth_dropped_global_topr"]
        + summary["truth_dropped_rerank_topk"]
        + summary["truth_missing_not_observed_in_scanned_posting"]
        + summary["truth_missing_not_in_posting_reserved"]
        - summary["truth_count"]
    )
    summary["payload_kb"] = summary["payload_physical_bytes"] / 1024.0
    summary["requested_kb"] = summary["requested_read_bytes"] / 1024.0
    summary["approx_single_thread_qps"] = 1000.0 / summary["total_latency_ms"] if summary["total_latency_ms"] > 0 else 0.0
    return summary


def read_matrix(path: str) -> List[Dict[str, str]]:
    with open(path, newline="") as f:
        return list(csv.DictReader(f, delimiter="\t"))


def main() -> int:
    parser = argparse.ArgumentParser(description="Summarize P2 topR sweep query_io_stats.csv files.")
    parser.add_argument("--matrix", required=True, help="run_matrix.tsv generated by run_spann_p2_topr_sweep.sh")
    parser.add_argument("--output", required=True, help="summary TSV output path")
    args = parser.parse_args()

    rows = read_matrix(args.matrix)
    output_fields = [
        "run_name",
        "search_thread_num",
        "posting_topr_per_posting",
        "posting_topr_global",
        "query_count",
        "recall",
        "total_latency_ms",
        "head_latency_ms",
        "ex_latency_ms",
        "batch_read_total_ms",
        "approx_single_thread_qps",
        "truth_count",
        "coarse_recall",
        "coarse_recall_after_dedupe",
        "rerank_recall",
        "final_recall",
        "truth_recovered_by_head_result",
        "truth_dropped_per_posting_topr",
        "truth_dropped_global_topr",
        "truth_dropped_rerank_topk",
        "truth_missing_not_observed_in_scanned_posting",
        "truth_missing_not_in_posting_reserved",
        "truth_attribution_closure_error",
        "unique_payload_pages",
        "payload_candidates",
        "candidates_per_payload_page",
        "postings_with_payload",
        "total_payload_page_spans",
        "pages_read",
        "payload_kb",
        "requested_kb",
        "distance_evaluated_count",
        "rerank_candidate_count",
        "coarse_candidate_count_before_dedupe",
        "coarse_candidate_count_after_dedupe",
        "query_csv",
    ]

    os.makedirs(os.path.dirname(os.path.abspath(args.output)), exist_ok=True)
    with open(args.output, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=output_fields, delimiter="\t")
        writer.writeheader()
        for row in rows:
            query_csv = row.get("query_csv", "")
            if not query_csv or not os.path.exists(query_csv):
                continue
            summary = summarize_csv(query_csv)
            output_row = {
                "run_name": row.get("run_name", ""),
                "search_thread_num": row.get("search_thread_num", ""),
                "posting_topr_per_posting": row.get("posting_topr_per_posting", ""),
                "posting_topr_global": row.get("posting_topr_global", ""),
                "query_csv": query_csv,
            }
            for metric in output_fields:
                if metric in output_row:
                    continue
                value = summary.get(metric, "")
                output_row[metric] = f"{value:.6f}" if isinstance(value, float) else value
            writer.writerow(output_row)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
